
name: helm-test
on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: kanthreg
  CLUSTER_NAME: sri-aks
  CLUSTER_RESOURCE_GROUP: sri-aks
  NAMESPACE: default
  JAVA_VERSION: '1.8'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2    
    
    # Connect to Azure Container registry (ACR)
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: kanthreg.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Container build
      run: |
        docker build -f $GITHUB_WORKSPACE/Dockerfile -t ${{ secrets.ACR }}/helmnodejs:${{ github.run_number }} .
    
    - name: Container push to a Azure Container registry (ACR)
      run: |
        docker push ${{ secrets.ACR }}/helmnodejs:${{ github.run_number }}
  helm-lint:
    name: Helm lint and release
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - uses: actions/checkout@v2
      - name: Helm Lint
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./mychart
      - name: Helm install
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install helm-demo ./mychart
          kubeconfig: '${{ secrets.KUBECONFIG }}'
